name: artroom-ldm
channels:
  - pytorch
  - defaults
dependencies:
  - git
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.19.2
  - pip:
    - gdown
    - albumentations==0.4.3
    - opencv-python==4.1.2.30
    - opencv-python-headless==4.1.2.30
    - pudb==2019.2
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.4.2
    - omegaconf==2.1.1
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - einops==0.3.0
    - torch-fidelity==0.3.0
    - transformers==4.19.2
    - torchmetrics==0.6.0
    - kornia==0.6
    - accelerate==0.12.0
    - pynvml==11.4.1
    - basicsr>=1.4.2
    - facexlib>=0.2.5
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - -e git+https://github.com/TencentARC/GFPGAN#egg=GFPGAN
    - -e git+https://github.com/xinntao/Real-ESRGAN#egg=realesrgan
    - -e git+https://github.com/hlky/k-diffusion-sd#egg=k_diffusion
    - -e .
